export const countries = [
  { code: 'AD', label: 'Andorra', dialCode: '376' },
  {
    code: 'AE',
    label: 'United Arab Emirates',
    dialCode: '971',
  },
  { code: 'AF', label: 'Afghanistan', dialCode: '93' },
  {
    code: 'AG',
    label: 'Antigua and Barbuda',
    dialCode: '1-268',
  },
  { code: 'AI', label: 'Anguilla', dialCode: '1-264' },
  { code: 'AL', label: 'Albania', dialCode: '355' },
  { code: 'AM', label: 'Armenia', dialCode: '374' },
  { code: 'AO', label: 'Angola', dialCode: '244' },
  { code: 'AQ', label: 'Antarctica', dialCode: '672' },
  { code: 'AR', label: 'Argentina', dialCode: '54' },
  { code: 'AS', label: 'American Samoa', dialCode: '1-684' },
  { code: 'AT', label: 'Austria', dialCode: '43' },
  {
    code: 'AU',
    label: 'Australia',
    dialCode: '61',
    suggested: true,
  },
  { code: 'AW', label: 'Aruba', dialCode: '297' },
  { code: 'AX', label: 'Alland Islands', dialCode: '358' },
  { code: 'AZ', label: 'Azerbaijan', dialCode: '994' },
  {
    code: 'BA',
    label: 'Bosnia and Herzegovina',
    dialCode: '387',
  },
  { code: 'BB', label: 'Barbados', dialCode: '1-246' },
  { code: 'BD', label: 'Bangladesh', dialCode: '880' },
  { code: 'BE', label: 'Belgium', dialCode: '32' },
  { code: 'BF', label: 'Burkina Faso', dialCode: '226' },
  { code: 'BG', label: 'Bulgaria', dialCode: '359' },
  { code: 'BH', label: 'Bahrain', dialCode: '973' },
  { code: 'BI', label: 'Burundi', dialCode: '257' },
  { code: 'BJ', label: 'Benin', dialCode: '229' },
  { code: 'BL', label: 'Saint Barthelemy', dialCode: '590' },
  { code: 'BM', label: 'Bermuda', dialCode: '1-441' },
  { code: 'BN', label: 'Brunei Darussalam', dialCode: '673' },
  { code: 'BO', label: 'Bolivia', dialCode: '591' },
  { code: 'BR', label: 'Brazil', dialCode: '55' },
  { code: 'BS', label: 'Bahamas', dialCode: '1-242' },
  { code: 'BT', label: 'Bhutan', dialCode: '975' },
  { code: 'BV', label: 'Bouvet Island', dialCode: '47' },
  { code: 'BW', label: 'Botswana', dialCode: '267' },
  { code: 'BY', label: 'Belarus', dialCode: '375' },
  { code: 'BZ', label: 'Belize', dialCode: '501' },
  {
    code: 'CA',
    label: 'Canada',
    dialCode: '1',
    suggested: true,
  },
  {
    code: 'CC',
    label: 'Cocos (Keeling) Islands',
    dialCode: '61',
  },
  {
    code: 'CD',
    label: 'Congo, Democratic Republic of the',
    dialCode: '243',
  },
  {
    code: 'CF',
    label: 'Central African Republic',
    dialCode: '236',
  },
  {
    code: 'CG',
    label: 'Congo, Republic of the',
    dialCode: '242',
  },
  { code: 'CH', label: 'Switzerland', dialCode: '41' },
  { code: 'CI', label: "Cote d'Ivoire", dialCode: '225' },
  { code: 'CK', label: 'Cook Islands', dialCode: '682' },
  { code: 'CL', label: 'Chile', dialCode: '56' },
  { code: 'CM', label: 'Cameroon', dialCode: '237' },
  { code: 'CN', label: 'China', dialCode: '86' },
  { code: 'CO', label: 'Colombia', dialCode: '57' },
  { code: 'CR', label: 'Costa Rica', dialCode: '506' },
  { code: 'CU', label: 'Cuba', dialCode: '53' },
  { code: 'CV', label: 'Cape Verde', dialCode: '238' },
  { code: 'CW', label: 'Curacao', dialCode: '599' },
  { code: 'CX', label: 'Christmas Island', dialCode: '61' },
  { code: 'CY', label: 'Cyprus', dialCode: '357' },
  { code: 'CZ', label: 'Czech Republic', dialCode: '420' },
  {
    code: 'DE',
    label: 'Germany',
    dialCode: '49',
    suggested: true,
  },
  { code: 'DJ', label: 'Djibouti', dialCode: '253' },
  { code: 'DK', label: 'Denmark', dialCode: '45' },
  { code: 'DM', label: 'Dominica', dialCode: '1-767' },
  {
    code: 'DO',
    label: 'Dominican Republic',
    dialCode: '1-809',
  },
  { code: 'DZ', label: 'Algeria', dialCode: '213' },
  { code: 'EC', label: 'Ecuador', dialCode: '593' },
  { code: 'EE', label: 'Estonia', dialCode: '372' },
  { code: 'EG', label: 'Egypt', dialCode: '20' },
  { code: 'EH', label: 'Western Sahara', dialCode: '212' },
  { code: 'ER', label: 'Eritrea', dialCode: '291' },
  { code: 'ES', label: 'Spain', dialCode: '34' },
  { code: 'ET', label: 'Ethiopia', dialCode: '251' },
  { code: 'FI', label: 'Finland', dialCode: '358' },
  { code: 'FJ', label: 'Fiji', dialCode: '679' },
  {
    code: 'FK',
    label: 'Falkland Islands (Malvinas)',
    dialCode: '500',
  },
  {
    code: 'FM',
    label: 'Micronesia, Federated States of',
    dialCode: '691',
  },
  { code: 'FO', label: 'Faroe Islands', dialCode: '298' },
  {
    code: 'FR',
    label: 'France',
    dialCode: '33',
    suggested: true,
  },
  { code: 'GA', label: 'Gabon', dialCode: '241' },
  { code: 'GB', label: 'United Kingdom', dialCode: '44' },
  { code: 'GD', label: 'Grenada', dialCode: '1-473' },
  { code: 'GE', label: 'Georgia', dialCode: '995' },
  { code: 'GF', label: 'French Guiana', dialCode: '594' },
  { code: 'GG', label: 'Guernsey', dialCode: '44' },
  { code: 'GH', label: 'Ghana', dialCode: '233' },
  { code: 'GI', label: 'Gibraltar', dialCode: '350' },
  { code: 'GL', label: 'Greenland', dialCode: '299' },
  { code: 'GM', label: 'Gambia', dialCode: '220' },
  { code: 'GN', label: 'Guinea', dialCode: '224' },
  { code: 'GP', label: 'Guadeloupe', dialCode: '590' },
  { code: 'GQ', label: 'Equatorial Guinea', dialCode: '240' },
  { code: 'GR', label: 'Greece', dialCode: '30' },
  {
    code: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    dialCode: '500',
  },
  { code: 'GT', label: 'Guatemala', dialCode: '502' },
  { code: 'GU', label: 'Guam', dialCode: '1-671' },
  { code: 'GW', label: 'Guinea-Bissau', dialCode: '245' },
  { code: 'GY', label: 'Guyana', dialCode: '592' },
  { code: 'HK', label: 'Hong Kong', dialCode: '852' },
  {
    code: 'HM',
    label: 'Heard Island and McDonald Islands',
    dialCode: '672',
  },
  { code: 'HN', label: 'Honduras', dialCode: '504' },
  { code: 'HR', label: 'Croatia', dialCode: '385' },
  { code: 'HT', label: 'Haiti', dialCode: '509' },
  { code: 'HU', label: 'Hungary', dialCode: '36' },
  { code: 'ID', label: 'Indonesia', dialCode: '62' },
  { code: 'IE', label: 'Ireland', dialCode: '353' },
  { code: 'IL', label: 'Israel', dialCode: '972' },
  { code: 'IM', label: 'Isle of Man', dialCode: '44' },
  { code: 'IN', label: 'India', dialCode: '91' },
  {
    code: 'IO',
    label: 'British Indian Ocean Territory',
    dialCode: '246',
  },
  { code: 'IQ', label: 'Iraq', dialCode: '964' },
  {
    code: 'IR',
    label: 'Iran, Islamic Republic of',
    dialCode: '98',
  },
  { code: 'IS', label: 'Iceland', dialCode: '354' },
  { code: 'IT', label: 'Italy', dialCode: '39' },
  { code: 'JE', label: 'Jersey', dialCode: '44' },
  { code: 'JM', label: 'Jamaica', dialCode: '1-876' },
  { code: 'JO', label: 'Jordan', dialCode: '962' },
  {
    code: 'JP',
    label: 'Japan',
    dialCode: '81',
    suggested: true,
  },
  { code: 'KE', label: 'Kenya', dialCode: '254' },
  { code: 'KG', label: 'Kyrgyzstan', dialCode: '996' },
  { code: 'KH', label: 'Cambodia', dialCode: '855' },
  { code: 'KI', label: 'Kiribati', dialCode: '686' },
  { code: 'KM', label: 'Comoros', dialCode: '269' },
  {
    code: 'KN',
    label: 'Saint Kitts and Nevis',
    dialCode: '1-869',
  },
  {
    code: 'KP',
    label: "Korea, Democratic People's Republic of",
    dialCode: '850',
  },
  { code: 'KR', label: 'Korea, Republic of', dialCode: '82' },
  { code: 'KW', label: 'Kuwait', dialCode: '965' },
  { code: 'KY', label: 'Cayman Islands', dialCode: '1-345' },
  { code: 'KZ', label: 'Kazakhstan', dialCode: '7' },
  {
    code: 'LA',
    label: "Lao People's Democratic Republic",
    dialCode: '856',
  },
  { code: 'LB', label: 'Lebanon', dialCode: '961' },
  { code: 'LC', label: 'Saint Lucia', dialCode: '1-758' },
  { code: 'LI', label: 'Liechtenstein', dialCode: '423' },
  { code: 'LK', label: 'Sri Lanka', dialCode: '94' },
  { code: 'LR', label: 'Liberia', dialCode: '231' },
  { code: 'LS', label: 'Lesotho', dialCode: '266' },
  { code: 'LT', label: 'Lithuania', dialCode: '370' },
  { code: 'LU', label: 'Luxembourg', dialCode: '352' },
  { code: 'LV', label: 'Latvia', dialCode: '371' },
  { code: 'LY', label: 'Libya', dialCode: '218' },
  { code: 'MA', label: 'Morocco', dialCode: '212' },
  { code: 'MC', label: 'Monaco', dialCode: '377' },
  {
    code: 'MD',
    label: 'Moldova, Republic of',
    dialCode: '373',
  },
  { code: 'ME', label: 'Montenegro', dialCode: '382' },
  {
    code: 'MF',
    label: 'Saint Martin (French part)',
    dialCode: '590',
  },
  { code: 'MG', label: 'Madagascar', dialCode: '261' },
  { code: 'MH', label: 'Marshall Islands', dialCode: '692' },
  {
    code: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
    dialCode: '389',
  },
  { code: 'ML', label: 'Mali', dialCode: '223' },
  { code: 'MM', label: 'Myanmar', dialCode: '95' },
  { code: 'MN', label: 'Mongolia', dialCode: '976' },
  { code: 'MO', label: 'Macao', dialCode: '853' },
  {
    code: 'MP',
    label: 'Northern Mariana Islands',
    dialCode: '1-670',
  },
  { code: 'MQ', label: 'Martinique', dialCode: '596' },
  { code: 'MR', label: 'Mauritania', dialCode: '222' },
  { code: 'MS', label: 'Montserrat', dialCode: '1-664' },
  { code: 'MT', label: 'Malta', dialCode: '356' },
  { code: 'MU', label: 'Mauritius', dialCode: '230' },
  { code: 'MV', label: 'Maldives', dialCode: '960' },
  { code: 'MW', label: 'Malawi', dialCode: '265' },
  { code: 'MX', label: 'Mexico', dialCode: '52' },
  { code: 'MY', label: 'Malaysia', dialCode: '60' },
  { code: 'MZ', label: 'Mozambique', dialCode: '258' },
  { code: 'NA', label: 'Namibia', dialCode: '264' },
  { code: 'NC', label: 'New Caledonia', dialCode: '687' },
  { code: 'NE', label: 'Niger', dialCode: '227' },
  { code: 'NF', label: 'Norfolk Island', dialCode: '672' },
  { code: 'NG', label: 'Nigeria', dialCode: '234' },
  { code: 'NI', label: 'Nicaragua', dialCode: '505' },
  { code: 'NL', label: 'Netherlands', dialCode: '31' },
  { code: 'NO', label: 'Norway', dialCode: '47' },
  { code: 'NP', label: 'Nepal', dialCode: '977' },
  { code: 'NR', label: 'Nauru', dialCode: '674' },
  { code: 'NU', label: 'Niue', dialCode: '683' },
  { code: 'NZ', label: 'New Zealand', dialCode: '64' },
  { code: 'OM', label: 'Oman', dialCode: '968' },
  { code: 'PA', label: 'Panama', dialCode: '507' },
  { code: 'PE', label: 'Peru', dialCode: '51' },
  { code: 'PF', label: 'French Polynesia', dialCode: '689' },
  { code: 'PG', label: 'Papua New Guinea', dialCode: '675' },
  { code: 'PH', label: 'Philippines', dialCode: '63' },
  { code: 'PK', label: 'Pakistan', dialCode: '92' },
  { code: 'PL', label: 'Poland', dialCode: '48' },
  {
    code: 'PM',
    label: 'Saint Pierre and Miquelon',
    dialCode: '508',
  },
  { code: 'PN', label: 'Pitcairn', dialCode: '870' },
  { code: 'PR', label: 'Puerto Rico', dialCode: '1' },
  {
    code: 'PS',
    label: 'Palestine, State of',
    dialCode: '970',
  },
  { code: 'PT', label: 'Portugal', dialCode: '351' },
  { code: 'PW', label: 'Palau', dialCode: '680' },
  { code: 'PY', label: 'Paraguay', dialCode: '595' },
  { code: 'QA', label: 'Qatar', dialCode: '974' },
  { code: 'RE', label: 'Reunion', dialCode: '262' },
  { code: 'RO', label: 'Romania', dialCode: '40' },
  { code: 'RS', label: 'Serbia', dialCode: '381' },
  { code: 'RU', label: 'Russian Federation', dialCode: '7' },
  { code: 'RW', label: 'Rwanda', dialCode: '250' },
  { code: 'SA', label: 'Saudi Arabia', dialCode: '966' },
  { code: 'SB', label: 'Solomon Islands', dialCode: '677' },
  { code: 'SC', label: 'Seychelles', dialCode: '248' },
  { code: 'SD', label: 'Sudan', dialCode: '249' },
  { code: 'SE', label: 'Sweden', dialCode: '46' },
  { code: 'SG', label: 'Singapore', dialCode: '65' },
  { code: 'SH', label: 'Saint Helena', dialCode: '290' },
  { code: 'SI', label: 'Slovenia', dialCode: '386' },
  {
    code: 'SJ',
    label: 'Svalbard and Jan Mayen',
    dialCode: '47',
  },
  { code: 'SK', label: 'Slovakia', dialCode: '421' },
  { code: 'SL', label: 'Sierra Leone', dialCode: '232' },
  { code: 'SM', label: 'San Marino', dialCode: '378' },
  { code: 'SN', label: 'Senegal', dialCode: '221' },
  { code: 'SO', label: 'Somalia', dialCode: '252' },
  { code: 'SR', label: 'Suriname', dialCode: '597' },
  { code: 'SS', label: 'South Sudan', dialCode: '211' },
  {
    code: 'ST',
    label: 'Sao Tome and Principe',
    dialCode: '239',
  },
  { code: 'SV', label: 'El Salvador', dialCode: '503' },
  {
    code: 'SX',
    label: 'Sint Maarten (Dutch part)',
    dialCode: '1-721',
  },
  {
    code: 'SY',
    label: 'Syrian Arab Republic',
    dialCode: '963',
  },
  { code: 'SZ', label: 'Swaziland', dialCode: '268' },
  {
    code: 'TC',
    label: 'Turks and Caicos Islands',
    dialCode: '1-649',
  },
  { code: 'TD', label: 'Chad', dialCode: '235' },
  {
    code: 'TF',
    label: 'French Southern Territories',
    dialCode: '262',
  },
  { code: 'TG', label: 'Togo', dialCode: '228' },
  { code: 'TH', label: 'Thailand', dialCode: '66' },
  { code: 'TJ', label: 'Tajikistan', dialCode: '992' },
  { code: 'TK', label: 'Tokelau', dialCode: '690' },
  { code: 'TL', label: 'Timor-Leste', dialCode: '670' },
  { code: 'TM', label: 'Turkmenistan', dialCode: '993' },
  { code: 'TN', label: 'Tunisia', dialCode: '216' },
  { code: 'TO', label: 'Tonga', dialCode: '676' },
  { code: 'TR', label: 'Turkey', dialCode: '90' },
  {
    code: 'TT',
    label: 'Trinidad and Tobago',
    dialCode: '1-868',
  },
  { code: 'TV', label: 'Tuvalu', dialCode: '688' },
  {
    code: 'TW',
    label: 'Taiwan, Republic of China',
    dialCode: '886',
  },
  {
    code: 'TZ',
    label: 'United Republic of Tanzania',
    dialCode: '255',
  },
  { code: 'UA', label: 'Ukraine', dialCode: '380' },
  { code: 'UG', label: 'Uganda', dialCode: '256' },
  {
    code: 'US',
    label: 'United States',
    dialCode: '1',
    suggested: true,
  },
  { code: 'UY', label: 'Uruguay', dialCode: '598' },
  { code: 'UZ', label: 'Uzbekistan', dialCode: '998' },
  {
    code: 'VA',
    label: 'Holy See (Vatican City State)',
    dialCode: '379',
  },
  {
    code: 'VC',
    label: 'Saint Vincent and the Grenadines',
    dialCode: '1-784',
  },
  { code: 'VE', label: 'Venezuela', dialCode: '58' },
  {
    code: 'VG',
    label: 'British Virgin Islands',
    dialCode: '1-284',
  },
  {
    code: 'VI',
    label: 'US Virgin Islands',
    dialCode: '1-340',
  },
  { code: 'VN', label: 'Vietnam', dialCode: '84' },
  { code: 'VU', label: 'Vanuatu', dialCode: '678' },
  { code: 'WF', label: 'Wallis and Futuna', dialCode: '681' },
  { code: 'WS', label: 'Samoa', dialCode: '685' },
  { code: 'XK', label: 'Kosovo', dialCode: '383' },
  { code: 'YE', label: 'Yemen', dialCode: '967' },
  { code: 'YT', label: 'Mayotte', dialCode: '262' },
  { code: 'ZA', label: 'South Africa', dialCode: '27' },
  { code: 'ZM', label: 'Zambia', dialCode: '260' },
  { code: 'ZW', label: 'Zimbabwe', dialCode: '263' },
];
